# name: Greetings

# on: [pull_request, issues]

# jobs:
#   greeting:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/first-interaction@v1
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
#         pr-message: |
#           Hello @${{ github.actor }}, thank you for submitting a PR! To allow your work to be integrated as seamlessly as possible, we advise you to:
#           - Verify your PR is **up-to-date with origin/master.**
#           - Verify all Continuous Integration (CI) **checks are passing**.
#           - Reduce changes to the absolute **minimum** required for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  -Bruce Lee

#         issue-message: |
#           Hello @${{ github.actor }}, thank you for your interest in our work!
            
#           If this is a bug report, please provide the **minimum viable code and steps to reproduce your issue**, otherwise we can not help you.
#           When submitting a new feature request or suggestion please make sure to check for duplicate issues.
